// Package hooks installs and manages git hooks for lnk.
package hooks

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/polymorcodeus/lnk/internal/lnkerror"
)

// Marker comments bracket a hook script written by lnk.
const (
	markerBegin = "# >>> lnk hook begin"
	markerEnd   = "# >>> lnk hook end"
)

// Hook names installed by lnk.
const (
	LnkRepoHook = "post-merge"
	ProjectHook = "post-checkout"
)

// InstallLnkRepo installs the post-merge hook in the lnk repository at
// repoPath. The hook invokes lnkBinary via 'lnk hooks run post-merge'.
func InstallLnkRepo(repoPath, lnkBinary string) error {
	return install(filepath.Join(repoPath, ".git", "hooks"), LnkRepoHook, lnkBinary, LnkRepoHook)
}

// InstallProject installs the post-checkout hook in a project repository at
// repoRoot. The hook invokes lnkBinary via 'lnk hooks run post-checkout'.
func InstallProject(repoRoot, lnkBinary string) error {
	return install(filepath.Join(repoRoot, ".git", "hooks"), ProjectHook, lnkBinary, ProjectHook)
}

// UninstallLnkRepo removes the post-merge hook from the lnk repository.
func UninstallLnkRepo(repoPath string) error {
	return uninstall(filepath.Join(repoPath, ".git", "hooks"), LnkRepoHook)
}

// UninstallProject removes the post-checkout hook from a project repository.
func UninstallProject(repoRoot string) error {
	return uninstall(filepath.Join(repoRoot, ".git", "hooks"), ProjectHook)
}

// IsInstalled reports whether the named hook in gitDir is managed by lnk.
func IsInstalled(gitDir, hookName string) bool {
	path := filepath.Join(gitDir, hookName)
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), markerBegin)
}

// install writes a shell hook script that delegates to lnkBinary. It refuses
// to overwrite an existing hook that was not written by lnk.
func install(gitDir, hookName, lnkBinary, runName string) error {
	if err := os.MkdirAll(gitDir, 0o755); err != nil {
		return fmt.Errorf("create hooks directory: %w", err)
	}

	path := filepath.Join(gitDir, hookName)
	if data, err := os.ReadFile(path); err == nil && len(data) > 0 {
		if !strings.Contains(string(data), markerBegin) {
			return lnkerror.WithPath(lnkerror.ErrForeignHook, path)
		}
	} else if err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("read existing hook %s: %w", path, err)
	}

	script := fmt.Sprintf(`#!/bin/sh
%s
# generated by lnk: do not edit
exec %s hooks run %s "$@"
%s
`, markerBegin, lnkBinary, runName, markerEnd)

	if err := os.WriteFile(path, []byte(script), 0o755); err != nil {
		return fmt.Errorf("write hook %s: %w", path, err)
	}
	return nil
}

// uninstall removes a lnk-managed hook. It is a no-op when the hook does not
// exist or is not managed by lnk.
func uninstall(gitDir, hookName string) error {
	path := filepath.Join(gitDir, hookName)
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		return fmt.Errorf("read hook %s: %w", path, err)
	}
	if !strings.Contains(string(data), markerBegin) {
		return nil
	}
	if err := os.Remove(path); err != nil {
		return fmt.Errorf("remove hook %s: %w", path, err)
	}
	return nil
}
